# Generated by Django 3.2.5 on 2021-07-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acheteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=80)),
                ('password', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=30)),
                ('codepostal', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vendeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=80)),
                ('password', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=30)),
                ('codepostal', models.IntegerField()),
            ],
        ),
    ]
