# Generated by Django 3.2.5 on 2021-07-15 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(max_length=50)),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('totalPoids', models.DecimalField(decimal_places=2, max_digits=8)),
                ('acheteur', models.ManyToManyField(null=True, to='users.Acheteur')),
            ],
        ),
        migrations.CreateModel(
            name='ProdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('alt', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('note', models.IntegerField()),
                ('description', models.CharField(max_length=150)),
                ('initPrice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('remisePrice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('remise', models.DecimalField(decimal_places=2, max_digits=8)),
                ('slug', models.SlugField(max_length=20)),
                ('poids', models.DecimalField(decimal_places=2, max_digits=8)),
                ('region', models.CharField(max_length=50)),
                ('best_sell', models.BooleanField()),
                ('disp_quantity', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.prodimage')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commande', models.ManyToManyField(null=True, to='products.Commande')),
                ('product', models.ManyToManyField(null=True, to='products.Product')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='product',
            field=models.ManyToManyField(null=True, to='products.Product'),
        ),
    ]
