# Generated by Django 3.2.5 on 2021-07-17 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acheteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=80)),
                ('password', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=30)),
                ('codepostal', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(max_length=50)),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('totalPoids', models.DecimalField(decimal_places=2, max_digits=8)),
                ('acheteur', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.acheteur')),
            ],
        ),
        migrations.CreateModel(
            name='ProdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('alt', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vendeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=80)),
                ('password', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=30)),
                ('codepostal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('note', models.IntegerField()),
                ('description', models.CharField(max_length=150)),
                ('initPrice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('remisePrice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('remise', models.DecimalField(decimal_places=2, max_digits=8)),
                ('slug', models.SlugField(max_length=20)),
                ('poids', models.DecimalField(decimal_places=2, max_digits=8)),
                ('region', models.CharField(max_length=50)),
                ('best_sell', models.BooleanField()),
                ('disp_quantity', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.prodimage')),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acheteur', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.acheteur')),
                ('product', models.ManyToManyField(null=True, to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default=None, max_length=50)),
                ('date_commande', models.DateField(default=None)),
                ('date_Liv', models.DateField(default=None)),
                ('acheteur', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.acheteur')),
                ('commande', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.commande')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acheteur', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.acheteur')),
                ('product', models.ManyToManyField(null=True, to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default=None, max_length=100)),
                ('date', models.DateField(default=None)),
                ('acheteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.acheteur')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=None)),
                ('commande', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.commande')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='product',
            field=models.ManyToManyField(null=True, to='products.Product'),
        ),
    ]
