# Generated by Django 3.2.5 on 2021-07-15 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='acheteur',
        ),
        migrations.AddField(
            model_name='commande',
            name='acheteur',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.acheteur'),
        ),
    ]
