# Generated by Django 3.2.5 on 2021-07-15 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210715_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandeline',
            name='commande',
        ),
        migrations.AddField(
            model_name='commandeline',
            name='commande',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.commande'),
        ),
        migrations.RemoveField(
            model_name='commandeline',
            name='product',
        ),
        migrations.AddField(
            model_name='commandeline',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
