# Generated by Django 3.2.5 on 2021-07-18 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_vendeur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vendeur',
        ),
    ]
