# Generated by Django 3.2.5 on 2021-07-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210715_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeline',
            name='quantity',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
