# Generated by Django 3.2.5 on 2021-07-18 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_vendeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendeur',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.vendeur'),
        ),
    ]
