# Generated by Django 3.2.5 on 2021-07-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_panier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='product',
        ),
        migrations.AddField(
            model_name='panier',
            name='product',
            field=models.ManyToManyField(null=True, to='products.Product'),
        ),
    ]
