# Generated by Django 3.2.5 on 2021-08-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210802_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='product',
        ),
        migrations.AddField(
            model_name='category',
            name='product',
            field=models.ManyToManyField(null=True, to='products.Product'),
        ),
    ]
