# Generated by Django 3.2.5 on 2021-08-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210802_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='product',
            field=models.ManyToManyField(null=True, related_name='product_sell', to='products.Product'),
        ),
    ]
