# Generated by Django 3.2.5 on 2021-07-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
