# Generated by Django 3.2.5 on 2021-08-08 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(null=True, to='products.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendeur',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='vendeur', to='products.vendeur'),
        ),
    ]
