# Generated by Django 3.2.5 on 2021-07-15 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('products', '0009_auto_20210715_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default=None, max_length=50)),
                ('date_commande', models.DateField(default=None)),
                ('date_Liv', models.DateField(default=None)),
                ('acheteur', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.acheteur')),
                ('commande', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.commande')),
            ],
        ),
    ]
